#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall `pkg-config gtkmm-3.0 --cflags` -fPIC -p
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = `pkg-config gtkmm-3.0 --libs ` -p

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/myprog

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/plotmm.so

OBJ_DEBUG = $(OBJDIR_DEBUG)/symbol.o $(OBJDIR_DEBUG)/supplemental.o $(OBJDIR_DEBUG)/scalediv.o $(OBJDIR_DEBUG)/scale.o $(OBJDIR_DEBUG)/plot.o $(OBJDIR_DEBUG)/paint.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/errorcurve.o $(OBJDIR_DEBUG)/doublerect.o $(OBJDIR_DEBUG)/doubleintmap.o $(OBJDIR_DEBUG)/curve.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/symbol.o $(OBJDIR_RELEASE)/supplemental.o $(OBJDIR_RELEASE)/scalediv.o $(OBJDIR_RELEASE)/scale.o $(OBJDIR_RELEASE)/plot.o $(OBJDIR_RELEASE)/paint.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/errorcurve.o $(OBJDIR_RELEASE)/doublerect.o $(OBJDIR_RELEASE)/doubleintmap.o $(OBJDIR_RELEASE)/curve.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/symbol.o: symbol.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c symbol.cc -o $(OBJDIR_DEBUG)/symbol.o

$(OBJDIR_DEBUG)/supplemental.o: supplemental.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c supplemental.cc -o $(OBJDIR_DEBUG)/supplemental.o

$(OBJDIR_DEBUG)/scalediv.o: scalediv.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c scalediv.cc -o $(OBJDIR_DEBUG)/scalediv.o

$(OBJDIR_DEBUG)/scale.o: scale.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c scale.cc -o $(OBJDIR_DEBUG)/scale.o

$(OBJDIR_DEBUG)/plot.o: plot.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c plot.cc -o $(OBJDIR_DEBUG)/plot.o

$(OBJDIR_DEBUG)/paint.o: paint.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c paint.cc -o $(OBJDIR_DEBUG)/paint.o

$(OBJDIR_DEBUG)/main.o: main.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cc -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/errorcurve.o: errorcurve.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c errorcurve.cc -o $(OBJDIR_DEBUG)/errorcurve.o

$(OBJDIR_DEBUG)/doublerect.o: doublerect.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c doublerect.cc -o $(OBJDIR_DEBUG)/doublerect.o

$(OBJDIR_DEBUG)/doubleintmap.o: doubleintmap.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c doubleintmap.cc -o $(OBJDIR_DEBUG)/doubleintmap.o

$(OBJDIR_DEBUG)/curve.o: curve.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c curve.cc -o $(OBJDIR_DEBUG)/curve.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/symbol.o: symbol.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c symbol.cc -o $(OBJDIR_RELEASE)/symbol.o

$(OBJDIR_RELEASE)/supplemental.o: supplemental.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c supplemental.cc -o $(OBJDIR_RELEASE)/supplemental.o

$(OBJDIR_RELEASE)/scalediv.o: scalediv.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c scalediv.cc -o $(OBJDIR_RELEASE)/scalediv.o

$(OBJDIR_RELEASE)/scale.o: scale.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c scale.cc -o $(OBJDIR_RELEASE)/scale.o

$(OBJDIR_RELEASE)/plot.o: plot.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c plot.cc -o $(OBJDIR_RELEASE)/plot.o

$(OBJDIR_RELEASE)/paint.o: paint.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c paint.cc -o $(OBJDIR_RELEASE)/paint.o

$(OBJDIR_RELEASE)/main.o: main.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cc -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/errorcurve.o: errorcurve.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c errorcurve.cc -o $(OBJDIR_RELEASE)/errorcurve.o

$(OBJDIR_RELEASE)/doublerect.o: doublerect.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c doublerect.cc -o $(OBJDIR_RELEASE)/doublerect.o

$(OBJDIR_RELEASE)/doubleintmap.o: doubleintmap.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c doubleintmap.cc -o $(OBJDIR_RELEASE)/doubleintmap.o

$(OBJDIR_RELEASE)/curve.o: curve.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c curve.cc -o $(OBJDIR_RELEASE)/curve.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

